model_list:
- model_name: gpt-4o
  litellm_params:
    model: azure/gpt-4o
    base_model: gpt-4o
    deployment_id: gpt-4o
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-4o
  litellm_params:
    model: azure/gpt-4o
    base_model: gpt-4o
    deployment_id: gpt-4o
    api_base: https://micl-swedencentral.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-4o
  litellm_params:
    model: azure/gpt-4o
    base_model: gpt-4o
    deployment_id: gpt-4o
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-4o-mini
  litellm_params:
    model: azure/gpt-4o-mini
    base_model: gpt-4o-mini
    deployment_id: gpt-4o-mini
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-4o-mini
  litellm_params:
    model: azure/gpt-4o-mini
    base_model: gpt-4o-mini
    deployment_id: gpt-4o-mini
    api_base: https://micl-swedencentral.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-4o-mini
  litellm_params:
    model: azure/gpt-4o-mini
    base_model: gpt-4o-mini
    deployment_id: gpt-4o-mini
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-5.2
  litellm_params:
    model: azure/gpt-5.2
    base_model: gpt-5.2
    deployment_id: gpt-5.2
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-5.2
  litellm_params:
    model: azure/gpt-5.2
    base_model: gpt-5.2
    deployment_id: gpt-5.2
    api_base: https://micl-swedencentral.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-5.2
  litellm_params:
    model: azure/gpt-5.2
    base_model: gpt-5.2
    deployment_id: gpt-5.2
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-5.2-chat
  litellm_params:
    model: azure/gpt-5.2-chat
    base_model: gpt-5.2-chat
    deployment_id: gpt-5.2-chat
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-5.2-chat
  litellm_params:
    model: azure/gpt-5.2-chat
    base_model: gpt-5.2-chat
    deployment_id: gpt-5.2-chat
    api_base: https://micl-swedencentral.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-5.2-chat
  litellm_params:
    model: azure/gpt-5.2-chat
    base_model: gpt-5.2-chat
    deployment_id: gpt-5.2-chat
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-5.1-codex
  litellm_params:
    model: azure/gpt-5.1-codex
    base_model: gpt-5.1-codex
    deployment_id: gpt-5.1-codex
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-5.1-codex
  litellm_params:
    model: azure/gpt-5.1-codex
    base_model: gpt-5.1-codex
    deployment_id: gpt-5.1-codex
    api_base: https://micl-swedencentral.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-5.1-codex
  litellm_params:
    model: azure/gpt-5.1-codex
    base_model: gpt-5.1-codex
    deployment_id: gpt-5.1-codex
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-image-1
  litellm_params:
    model: azure/gpt-image-1
    base_model: gpt-image-1
    deployment_id: gpt-image-1
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-image-1
  litellm_params:
    model: azure/gpt-image-1
    base_model: gpt-image-1
    deployment_id: gpt-image-1
    api_base: https://micl-swedencentral.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: gpt-image-1
  litellm_params:
    model: azure/gpt-image-1
    base_model: gpt-image-1
    deployment_id: gpt-image-1
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: sora-2
  litellm_params:
    model: azure/sora-2
    base_model: sora-2
    deployment_id: sora-2
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: sora-2
  litellm_params:
    model: azure/sora-2
    base_model: sora-2
    deployment_id: sora-2
    api_base: https://micl-swedencentral.openai.azure.com/
    api_version: 2025-04-01-preview
- model_name: sora-2
  litellm_params:
    model: azure/sora-2
    base_model: sora-2
    deployment_id: sora-2
    api_base: https://micl-eastus2-2.openai.azure.com/
    api_version: 2025-04-01-preview
litellm_settings:
  enable_azure_ad_token_refresh: true
router_settings:
  routing_strategy: simple-shuffle
  num_retries: 2
